
services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks:
      - inc_network
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inc_network
    env_file:
      - .env
    restart: always
  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inc_network
    env_file:
      - .env
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIR}/wordpress
      o: bind

networks:
  inc_network:
    driver: bridge