FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y nginx &&\
    apt-get install -y openssl \
    && rm -rf /var/lib/apt/lists/* 

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout \
    /etc/ssl/private/nginx-selfsigned.key -out \
    /etc/ssl/certs/nginx-selfsigned.crt -subj "/CN=yael-yas.42.fr"

COPY conf/nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT [ "nginx" , "-g", "daemon off;"]
