events {
    worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;

	server {
		listen 443 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;

		ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
		ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

		root /var/www/html;
		server_name yael-yas.42.fr;
		index index.php index.html index.htm;
		client_max_body_size 64M;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
		}
	}
}

