FROM debian:bookworm-slim

RUN apt-get update -i && \
    apt-get install -y curl \
    wget \
    php8.2 \
    php8.2-fpm \
    php8.2-mysql \
    mariadb-client \
    && rm -rf /var/lib/apt/lists/*

